from .hcaptcha_classification import HCaptchaClassification
from .hcaptcha_task_proxyless import HCaptchaTaskProxyless
from .image_to_text_task import ImageToTextTask
from .no_captcha_task_proxyless import NoCaptchaTaskProxyless
from .re_captcha_v2_classification import ReCaptchaV2Classification
from .recaptcha_v2_enterprise_task_proxyless import RecaptchaV2EnterpriseTaskProxyless
from .recaptcha_v3_enterprise_task import RecaptchaV3EnterpriseTask
from .recaptcha_v3_task_proxyless import RecaptchaV3TaskProxyless
